"""
build_pages.py — the second half of the R -> static-site pipeline.

Input:  site/data.json   (produced by tools/convert_r_to_json.py
                           from app.R + schemes_data.R)
Output: site/data.js                  (adds a url-safe `slug` and extracted
                                        `links` [{label, url}] to every scheme)
        site/schemes/<slug>.html      (one static detail page per scheme)

Run with: python3 build_pages.py
Requires only the Python standard library.
"""
import json
import os
import re
import unicodedata

SITE_DIR = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SCHEMES_DIR = os.path.join(SITE_DIR, "schemes")
os.makedirs(SCHEMES_DIR, exist_ok=True)

with open(os.path.join(SITE_DIR, "data.json"), encoding="utf-8") as f:
    data = json.load(f)

content = data["content"]
agent_warning = data["agent_warning"]
all_schemes = data["all_schemes"]

# ---------------------------------------------------------------
# 1. Slugs — unique, url-safe, stable (based on the English name)
# ---------------------------------------------------------------
def slugify(text):
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return text or "scheme"

seen = {}
for row in all_schemes:
    base = slugify(row["name_en"])
    if base in seen:
        seen[base] += 1
        slug = f"{base}-{seen[base]}"
    else:
        seen[base] = 0
        slug = base
    row["slug"] = slug

# ---------------------------------------------------------------
# 2. Pull out portal / contact links from free-text apply+contact
#    fields, e.g. "swasthyasathi.gov.in", "pmkisan.gov.in".
# ---------------------------------------------------------------
DOMAIN_RE = re.compile(
    r"\b((?:[a-zA-Z0-9][a-zA-Z0-9\-]*\.)+(?:gov\.in|nic\.in|org\.in|co\.in|ac\.in|com|org|net|in))\b"
)

def find_links(row):
    haystack = f"{row.get('apply','')} {row.get('contact','')}"
    found = []
    seen_domains = set()
    for m in DOMAIN_RE.finditer(haystack):
        domain = m.group(1).rstrip(".")
        # trim any trailing junk that isn't part of a real domain
        if domain.lower() in seen_domains:
            continue
        seen_domains.add(domain.lower())
        found.append({"label": domain, "url": "https://" + domain})
    return found

import urllib.parse

for row in all_schemes:
    links = find_links(row)
    row["has_official_link"] = bool(links)
    if not links:
        # No real domain in the source data — never fabricate a .gov.in
        # URL, since a wrong guess is worse than none. Point to a search
        # instead so the person can still find the right page themselves.
        q = urllib.parse.quote(f"{row['name_en']} West Bengal government scheme official site")
        links = [{
            "label": "Search for the official page",
            "url": f"https://www.google.com/search?q={q}",
        }]
    row["links"] = links

# ---------------------------------------------------------------
# 3. Map troubleshooting-tree scheme keys to directory rows, so a
#    scheme page can cross-link to "Fix a problem" when relevant.
# ---------------------------------------------------------------
TROUBLESHOOT_MATCH = {
    "Annapurna Bhandar (formerly Lakshmir Bhandar)": "annapurna",
    "Ration Card (NFSA / Khadya Sathi)": "ration",
    "Swasthya Sathi": "swasthya",
    "Ayushman Bharat (PM-JAY)": "swasthya",
}
def troubleshoot_key_for(name_en):
    return TROUBLESHOOT_MATCH.get(name_en)

for row in all_schemes:
    row["troubleshoot_key"] = troubleshoot_key_for(row["name_en"])

# ---------------------------------------------------------------
# 4. Write data.js (adds slug/links/troubleshoot_key to ALL_SCHEMES)
# ---------------------------------------------------------------
with open(os.path.join(SITE_DIR, "data.js"), "w", encoding="utf-8") as f:
    f.write("// Auto-generated by tools/convert_r_to_json.py + tools/build_pages.py\n")
    f.write("// Do not hand-edit; regenerate from the source R files instead.\n")
    f.write("const CONTENT = " + json.dumps(content, ensure_ascii=False) + ";\n")
    f.write("const AGENT_WARNING = " + json.dumps(agent_warning, ensure_ascii=False) + ";\n")
    f.write("const ALL_SCHEMES = " + json.dumps(all_schemes, ensure_ascii=False) + ";\n")

# ---------------------------------------------------------------
# 5. Render one static HTML page per scheme
# ---------------------------------------------------------------
PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="bn">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{name_en} · আপনার অধিকার · Aponar Adhikar</title>
<meta name="description" content="{benefit_escaped}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Tiro+Bangla:ital@0;1&family=Hind+Siliguri:wght@400;500;600;700&display=swap">
<link rel="stylesheet" href="../styles.css">
</head>
<body>

<header class="site-header">
  <div class="site-header-inner">
    <a href="../index.html" style="text-decoration:none;">
      <div class="brand-bn">আপনার অধিকার</div>
      <div class="brand-en">Aponar Adhikar &middot; Your Entitlement</div>
    </a>
    <nav class="site-nav">
      <a href="../index.html#home">হোম · Home</a>
      <a href="../index.html#fix">সমস্যার সমাধান · Fix a problem</a>
      <a href="../index.html#browse" class="active">সব প্রকল্প · Browse schemes</a>
    </nav>
  </div>
</header>

<div class="app-wrap wide">
  <a href="../index.html#browse" class="crumb-back">&larr; সব প্রকল্প &middot; Back to all schemes</a>

  <div class="card scheme-detail">
    <div class="scheme-row-top">
      <div>
        <h1>{name_en}</h1>
        {name_bn_block}
      </div>
      <div class="cat-badge">{category}</div>
    </div>

    <div class="status-line">{status}</div>

    <div class="detail-block">
      <div class="detail-label">সুবিধা &middot; Benefit</div>
      <div class="detail-value benefit-line">{benefit}</div>
    </div>

    <div class="detail-block">
      <div class="detail-label">কীভাবে আবেদন করবেন &middot; How to apply</div>
      <div class="detail-value">{apply}</div>
    </div>

    <div class="detail-block">
      <div class="detail-label">যোগাযোগ &middot; Contact</div>
      <div class="detail-value">{contact}</div>
    </div>

    {links_block}
    {troubleshoot_block}
  </div>
</div>

<footer class="app-footer">
  This is an independent, unofficial tool and is not affiliated with the Government of West Bengal. Scheme rules changed significantly in 2026 &mdash; always confirm final details on the relevant official portal or at a Duare Sarkar camp before applying.<br>
  এটি একটি স্বাধীন, বেসরকারি সহায়ক টুল এবং পশ্চিমবঙ্গ সরকারের সাথে যুক্ত নয়।
</footer>

</body>
</html>
"""

def esc(s):
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def render_scheme_page(row):
    name_bn_block = f'<div class="bn-name-lg">{esc(row["name_bn"])}</div>' if row.get("name_bn") else ""

    link_class = "btn-primary" if row["has_official_link"] else "btn-secondary"
    items = "\n".join(
        f'<a class="{link_class} link-btn" href="{l["url"]}" target="_blank" rel="noopener">{esc(l["label"])} &rarr;</a>'
        for l in row["links"]
    )
    link_heading = "সরকারি পোর্টাল &middot; Official links" if row["has_official_link"] else "পোর্টাল খুঁজুন &middot; Find the official page"
    link_note = "" if row["has_official_link"] else '<p class="link-note">No official URL was listed in our source data for this scheme &mdash; this searches for it instead of guessing.</p>'
    links_block = f'''<div class="detail-block">
      <div class="detail-label">{link_heading}</div>
      {link_note}
      <div class="link-btn-row">{items}</div>
    </div>'''

    tkey = row.get("troubleshoot_key")
    if tkey:
        sc = content[tkey]
        troubleshoot_block = f'''<div class="callout-card">
      <div>
        <strong>এই প্রকল্পে সমস্যা হচ্ছে?</strong> &middot; Having a problem with this scheme?<br>
        <span style="color:var(--ink-soft);font-size:13.5px;">Payment stuck, application rejected, or card not accepted — get a step-by-step answer.</span>
      </div>
      <a href="../index.html#fix" class="btn-primary link-btn">সমস্যার সমাধান খুঁজুন &middot; Fix this &rarr;</a>
    </div>'''
    else:
        troubleshoot_block = ""

    html = PAGE_TEMPLATE.format(
        name_en=esc(row["name_en"]),
        benefit_escaped=esc(row["benefit"]),
        name_bn_block=name_bn_block,
        category=esc(row["category"]),
        status=esc(row["status"]),
        benefit=esc(row["benefit"]),
        apply=esc(row["apply"]),
        contact=esc(row["contact"]),
        links_block=links_block,
        troubleshoot_block=troubleshoot_block,
    )
    with open(os.path.join(SCHEMES_DIR, row["slug"] + ".html"), "w", encoding="utf-8") as f:
        f.write(html)

for row in all_schemes:
    render_scheme_page(row)

print(f"Wrote {len(all_schemes)} scheme pages to {SCHEMES_DIR}")
print("Sample slugs:", [r["slug"] for r in all_schemes[:5]])
dupes = [s for s, n in seen.items() if n > 0]
print("Slugs that needed de-duplication:", dupes)